language: erlang

otp_release:
  - R16B03
  - 17.0
  - 17.1
  - 17.4
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
  - 19.1
  - 19.2
  - 19.3
  - 20.0

script: PATH=.:$PATH make update test dialyzer coveralls

install: wget https://github.com/erlang/rebar3/releases/download/3.4.4/rebar3 && chmod 755 rebar3

